table Dim_Vendedor
	lineageTag: 472e726a-3a2b-4675-ac7f-402757287170

	column ID_Vendedor
		dataType: int64
		formatString: 0
		lineageTag: f3033d4a-017c-4e17-afb0-b186111c4702
		summarizeBy: none
		sourceColumn: ID_Vendedor

		annotation SummarizationSetBy = Automatic

	column Vendedor
		dataType: string
		lineageTag: 6ec47ef9-14f7-44e6-b3eb-f25eeb8f442d
		summarizeBy: none
		sourceColumn: Vendedor

		annotation SummarizationSetBy = Automatic

	column fecha_nacimiento
		dataType: dateTime
		formatString: General Date
		lineageTag: 80b5e8d8-8218-4d68-96a6-ed29f551f7f6
		summarizeBy: none
		sourceColumn: fecha_nacimiento

		variation Variation
			isDefault
			relationship: 5892fcdb-abb9-4a6b-a97b-6a02ef98de4b
			defaultHierarchy: LocalDateTable_56791247-f3f5-405c-b83e-e9e0dcd3232d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Foto
		dataType: string
		lineageTag: 9851aab5-b9b4-4978-a556-ac649e4808a7
		summarizeBy: none
		sourceColumn: Foto

		annotation SummarizationSetBy = Automatic

	partition Dim_Vendedor = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\natal_5bvjz7f\Downloads\VentasVehiculos.xlsx"), null, true),
				    Dim_Vendedor_Table = Source{[Item="Dim_Vendedor",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Dim_Vendedor_Table,{{"ID_Vendedor", Int64.Type}, {"Vendedor", type text}, {"fecha_nacimiento", type datetime}, {"Foto", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

