table dim_vehiculo
	lineageTag: f89b7daf-495d-4c62-91b8-44b060c9b118

	column id_vehiculo
		dataType: int64
		formatString: 0
		lineageTag: 970958db-8fca-4208-adad-377a9512da5e
		summarizeBy: none
		sourceColumn: id_vehiculo

		annotation SummarizationSetBy = Automatic

	column marca_vehiculo
		dataType: string
		lineageTag: e3cf87a0-32b4-4a1c-8722-94f9b73e86b1
		summarizeBy: none
		sourceColumn: marca_vehiculo

		annotation SummarizationSetBy = Automatic

	column modelo_vehiculo
		dataType: string
		lineageTag: 8c6eb051-9e78-4299-8bcc-78ceedd12339
		summarizeBy: none
		sourceColumn: modelo_vehiculo

		annotation SummarizationSetBy = Automatic

	column tipo_vehiculo
		dataType: string
		lineageTag: 2521b938-b900-4b3a-b53c-c55eccef5ec8
		summarizeBy: none
		sourceColumn: tipo_vehiculo

		annotation SummarizationSetBy = Automatic

	column año_vehiculo
		dataType: int64
		formatString: 0
		lineageTag: 042689e3-6c41-4f46-ab56-8d14be552fc9
		summarizeBy: sum
		sourceColumn: año_vehiculo

		annotation SummarizationSetBy = Automatic

	partition dim_vehiculo = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\natal_5bvjz7f\Downloads\VentasVehiculos.xlsx"), null, true),
				    dim_vehiculo_Table = Source{[Item="dim_vehiculo",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dim_vehiculo_Table,{{"id_vehiculo", Int64.Type}, {"marca_vehiculo", type text}, {"modelo_vehiculo", type text}, {"tipo_vehiculo", type text}, {"año_vehiculo", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

